package com.github.theredbrain.overhauleddamage.entity;

import com.github.theredbrain.overhauleddamage.OverhauledDamage;
import com.google.common.collect.HashMultimap;
import net.minecraft.core.Holder;
import net.minecraft.world.entity.ai.attributes.Attribute;
import net.minecraft.world.entity.ai.attributes.AttributeModifier;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.entity.player.Player;

public class PlayerHelper {

	public static void tick(Player player) {
		if (!player.level().isClientSide()) {
			// apply natural attribute modifiers
			player.getAttributes().addTransientAttributeModifiers(getNaturalAttributeModifiers());
		}
	}

	private static HashMultimap<Holder<Attribute>, AttributeModifier> getNaturalAttributeModifiers() {
		HashMultimap<Holder<Attribute>, AttributeModifier> hashMultimap = HashMultimap.create();
		hashMultimap.put(Attributes.ARMOR_TOUGHNESS, new AttributeModifier(OverhauledDamage.identifier("natural_armour_toughness_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_armor_toughness.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.ADDITIONAL_BASHING_DAMAGE, new AttributeModifier(OverhauledDamage.identifier("natural_additional_bashing_damage_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_additional_bashing_damage.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.INCREASED_BASHING_DAMAGE, new AttributeModifier(OverhauledDamage.identifier("natural_increased_bashing_damage_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_increased_bashing_damage.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.BASHING_RESISTANCE, new AttributeModifier(OverhauledDamage.identifier("natural_bashing_resistance_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_bashing_resistance.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.ADDITIONAL_PIERCING_DAMAGE, new AttributeModifier(OverhauledDamage.identifier("natural_additional_piercing_damage_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_additional_piercing_damage.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.INCREASED_PIERCING_DAMAGE, new AttributeModifier(OverhauledDamage.identifier("natural_increased_piercing_damage_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_increased_piercing_damage.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.PIERCING_RESISTANCE, new AttributeModifier(OverhauledDamage.identifier("natural_piercing_resistance_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_piercing_resistance.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.ADDITIONAL_SLASHING_DAMAGE, new AttributeModifier(OverhauledDamage.identifier("natural_additional_slashing_damage_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_additional_slashing_damage.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.INCREASED_SLASHING_DAMAGE, new AttributeModifier(OverhauledDamage.identifier("natural_increased_slashing_damage_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_increased_slashing_damage.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.SLASHING_RESISTANCE, new AttributeModifier(OverhauledDamage.identifier("natural_slashing_resistance_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_slashing_resistance.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.BLOCKED_PHYSICAL_DAMAGE, new AttributeModifier(OverhauledDamage.identifier("natural_blocked_physical_damage_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_blocked_physical_damage.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.MAX_BLEEDING_BUILD_UP, new AttributeModifier(OverhauledDamage.identifier("natural_max_bleeding_build_up_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_max_bleeding_build_up.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.BLEEDING_DURATION, new AttributeModifier(OverhauledDamage.identifier("natural_bleeding_duration_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_bleeding_duration.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.BLEEDING_TICK_THRESHOLD, new AttributeModifier(OverhauledDamage.identifier("natural_bleeding_tick_threshold_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_bleeding_tick_threshold.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.BLEEDING_BUILD_UP_REDUCTION, new AttributeModifier(OverhauledDamage.identifier("natural_bleeding_build_up_reduction_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_bleeding_build_up_reduction.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.BLEEDING_BUILD_UP_REDUCTION_DELAY_THRESHOLD, new AttributeModifier(OverhauledDamage.identifier("natural_bleeding_build_up_reduction_delay_threshold_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_bleeding_build_up_reduction_delay_threshold.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.ADDITIONAL_FROST_DAMAGE, new AttributeModifier(OverhauledDamage.identifier("natural_additional_frost_damage_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_additional_frost_damage.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.INCREASED_FROST_DAMAGE, new AttributeModifier(OverhauledDamage.identifier("natural_increased_frost_damage_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_increased_frost_damage.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.BLOCKED_FROST_DAMAGE, new AttributeModifier(OverhauledDamage.identifier("natural_blocked_frost_damage_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_blocked_frost_damage.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.FROST_RESISTANCE, new AttributeModifier(OverhauledDamage.identifier("natural_frost_resistance_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_frost_resistance.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.MAX_FREEZE_BUILD_UP, new AttributeModifier(OverhauledDamage.identifier("natural_max_freeze_build_up_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_max_freeze_build_up.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.FREEZE_DURATION, new AttributeModifier(OverhauledDamage.identifier("natural_freeze_duration_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_freeze_duration.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.FREEZE_TICK_THRESHOLD, new AttributeModifier(OverhauledDamage.identifier("natural_freeze_tick_threshold_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_freeze_tick_threshold.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.FREEZE_BUILD_UP_REDUCTION, new AttributeModifier(OverhauledDamage.identifier("natural_freeze_build_up_reduction_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_freeze_build_up_reduction.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.FREEZE_BUILD_UP_REDUCTION_DELAY_THRESHOLD, new AttributeModifier(OverhauledDamage.identifier("natural_freeze_build_up_reduction_delay_threshold_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_freeze_build_up_reduction_delay_threshold.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.ADDITIONAL_FIRE_DAMAGE, new AttributeModifier(OverhauledDamage.identifier("natural_additional_fire_damage_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_additional_fire_damage.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.INCREASED_FIRE_DAMAGE, new AttributeModifier(OverhauledDamage.identifier("natural_increased_fire_damage_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_increased_fire_damage.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.BLOCKED_FIRE_DAMAGE, new AttributeModifier(OverhauledDamage.identifier("natural_blocked_fire_damage_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_blocked_fire_damage.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.FIRE_RESISTANCE, new AttributeModifier(OverhauledDamage.identifier("natural_fire_resistance_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_fire_resistance.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.MAX_BURN_BUILD_UP, new AttributeModifier(OverhauledDamage.identifier("natural_max_burn_build_up_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_max_burn_build_up.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.BURN_DURATION, new AttributeModifier(OverhauledDamage.identifier("natural_burn_duration_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_burn_duration.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.BURN_TICK_THRESHOLD, new AttributeModifier(OverhauledDamage.identifier("natural_burn_tick_threshold_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_burn_tick_threshold.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.BURN_BUILD_UP_REDUCTION, new AttributeModifier(OverhauledDamage.identifier("natural_burn_build_up_reduction_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_burn_build_up_reduction.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.BURN_BUILD_UP_REDUCTION_DELAY_THRESHOLD, new AttributeModifier(OverhauledDamage.identifier("natural_burn_build_up_reduction_delay_threshold_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_burn_build_up_reduction_delay_threshold.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.ADDITIONAL_LIGHTNING_DAMAGE, new AttributeModifier(OverhauledDamage.identifier("natural_additional_lightning_damage_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_additional_lightning_damage.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.INCREASED_LIGHTNING_DAMAGE, new AttributeModifier(OverhauledDamage.identifier("natural_increased_lightning_damage_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_increased_lightning_damage.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.BLOCKED_LIGHTNING_DAMAGE, new AttributeModifier(OverhauledDamage.identifier("natural_blocked_lightning_damage_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_blocked_lightning_damage.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.LIGHTNING_RESISTANCE, new AttributeModifier(OverhauledDamage.identifier("natural_lightning_resistance_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_lightning_resistance.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.MAX_SHOCK_BUILD_UP, new AttributeModifier(OverhauledDamage.identifier("natural_max_shock_build_up_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_max_shock_build_up.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.SHOCK_DURATION, new AttributeModifier(OverhauledDamage.identifier("natural_shock_duration_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_shock_duration.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.SHOCK_TICK_THRESHOLD, new AttributeModifier(OverhauledDamage.identifier("natural_shock_tick_threshold_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_shock_tick_threshold.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.SHOCK_BUILD_UP_REDUCTION, new AttributeModifier(OverhauledDamage.identifier("natural_shock_build_up_reduction_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_shock_build_up_reduction.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.SHOCK_BUILD_UP_REDUCTION_DELAY_THRESHOLD, new AttributeModifier(OverhauledDamage.identifier("natural_shock_build_up_reduction_delay_threshold_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_shock_build_up_reduction_delay_threshold.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.ADDITIONAL_POISON_DAMAGE, new AttributeModifier(OverhauledDamage.identifier("natural_additional_poison_damage_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_additional_poison_damage.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.INCREASED_POISON_DAMAGE, new AttributeModifier(OverhauledDamage.identifier("natural_increased_poison_damage_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_increased_poison_damage.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.BLOCKED_POISON_DAMAGE, new AttributeModifier(OverhauledDamage.identifier("natural_blocked_poison_damage_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_blocked_poison_damage.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.POISON_RESISTANCE, new AttributeModifier(OverhauledDamage.identifier("natural_poison_resistance_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_poison_resistance.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.MAX_POISON_BUILD_UP, new AttributeModifier(OverhauledDamage.identifier("natural_max_poison_build_up_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_max_poison_build_up.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.POISON_DURATION, new AttributeModifier(OverhauledDamage.identifier("natural_poison_duration_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_poison_duration.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.POISON_TICK_THRESHOLD, new AttributeModifier(OverhauledDamage.identifier("natural_poison_tick_threshold_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_poison_tick_threshold.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.POISON_BUILD_UP_REDUCTION, new AttributeModifier(OverhauledDamage.identifier("natural_poison_build_up_reduction_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_poison_build_up_reduction.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.POISON_BUILD_UP_REDUCTION_DELAY_THRESHOLD, new AttributeModifier(OverhauledDamage.identifier("natural_poison_build_up_reduction_delay_threshold_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_poison_build_up_reduction_delay_threshold.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.MAX_STAGGER_BUILD_UP, new AttributeModifier(OverhauledDamage.identifier("natural_max_stagger_build_up_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_max_stagger_build_up.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.STAGGER_DURATION, new AttributeModifier(OverhauledDamage.identifier("natural_stagger_duration_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_stagger_duration.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.STAGGER_TICK_THRESHOLD, new AttributeModifier(OverhauledDamage.identifier("natural_stagger_tick_threshold_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_stagger_tick_threshold.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.STAGGER_BUILD_UP_REDUCTION, new AttributeModifier(OverhauledDamage.identifier("natural_stagger_build_up_reduction_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_stagger_build_up_reduction.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.STAGGER_BUILD_UP_REDUCTION_DELAY_THRESHOLD, new AttributeModifier(OverhauledDamage.identifier("natural_stagger_build_up_reduction_delay_threshold_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_stagger_build_up_reduction_delay_threshold.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.DAMAGE_TAKEN_FROM_MANA_MULTIPLIER, new AttributeModifier(OverhauledDamage.identifier("natural_damage_taken_from_mana_multiplier_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_damage_taken_from_mana_multiplier.get(), AttributeModifier.Operation.ADD_VALUE));
		hashMultimap.put(OverhauledDamage.DAMAGE_TAKEN_FROM_STAMINA_MULTIPLIER, new AttributeModifier(OverhauledDamage.identifier("natural_damage_taken_from_stamina_multiplier_modifier"), OverhauledDamage.SERVER_CONFIG.natural_player_attribute_values.natural_damage_taken_from_stamina_multiplier.get(), AttributeModifier.Operation.ADD_VALUE));
		return hashMultimap;
	}

}
