package com.github.theredbrain.overhauleddamage.mixin.entity.attribute;

import com.github.theredbrain.overhauleddamage.OverhauledDamage;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.entity.ai.attributes.RangedAttribute;
import org.spongepowered.asm.mixin.Mixin;

@Mixin(Attributes.class)
public class EntityAttributesMixin {
	static {
		OverhauledDamage.ADDITIONAL_BASHING_DAMAGE = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.additional_bashing_damage"), new RangedAttribute("attribute.name.generic.additional_bashing_damage", 0.0, -1024.0, 1024.0).setSyncable(true));
		OverhauledDamage.INCREASED_BASHING_DAMAGE = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.increased_bashing_damage"), new RangedAttribute("attribute.name.generic.increased_bashing_damage", 1.0, -1024.0, 1024.0).setSyncable(true));
		OverhauledDamage.BASHING_RESISTANCE = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.bashing_resistance"), new RangedAttribute("attribute.name.generic.bashing_resistance", 0.0, -1024.0, 1024.0).setSyncable(true));

		OverhauledDamage.ADDITIONAL_PIERCING_DAMAGE = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.additional_piercing_damage"), new RangedAttribute("attribute.name.generic.additional_piercing_damage", 0.0, -1024.0, 1024.0).setSyncable(true));
		OverhauledDamage.INCREASED_PIERCING_DAMAGE = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.increased_piercing_damage"), new RangedAttribute("attribute.name.generic.increased_piercing_damage", 1.0, -1024.0, 1024.0).setSyncable(true));
		OverhauledDamage.PIERCING_RESISTANCE = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.piercing_resistance"), new RangedAttribute("attribute.name.generic.piercing_resistance", 0.0, -1024.0, 1024.0).setSyncable(true));

		OverhauledDamage.ADDITIONAL_SLASHING_DAMAGE = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.additional_slashing_damage"), new RangedAttribute("attribute.name.generic.additional_slashing_damage", 0.0, -1024.0, 1024.0).setSyncable(true));
		OverhauledDamage.INCREASED_SLASHING_DAMAGE = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.increased_slashing_damage"), new RangedAttribute("attribute.name.generic.increased_slashing_damage", 1.0, -1024.0, 1024.0).setSyncable(true));
		OverhauledDamage.SLASHING_RESISTANCE = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.slashing_resistance"), new RangedAttribute("attribute.name.generic.slashing_resistance", 0.0, -1024.0, 1024.0).setSyncable(true));

		OverhauledDamage.BLOCKED_PHYSICAL_DAMAGE = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.blocked_physical_damage"), new RangedAttribute("attribute.name.generic.blocked_physical_damage", 0.0, 0.0, 1024.0).setSyncable(true));

		OverhauledDamage.MAX_BLEEDING_BUILD_UP = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.max_bleeding_build_up"), new RangedAttribute("attribute.name.generic.max_bleeding_build_up", 20.0, -1.0, 1024.0).setSyncable(true));
		OverhauledDamage.BLEEDING_DURATION = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.bleeding_duration"), new RangedAttribute("attribute.name.generic.bleeding_duration", 201.0, 1.0, 1000000.0).setSyncable(true));
		OverhauledDamage.BLEEDING_TICK_THRESHOLD = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.bleeding_tick_threshold"), new RangedAttribute("attribute.name.generic.bleeding_tick_threshold", 20.0, 0.0, 1024.0).setSyncable(true));
		OverhauledDamage.BLEEDING_BUILD_UP_REDUCTION = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.bleeding_build_up_reduction"), new RangedAttribute("attribute.name.generic.bleeding_build_up_reduction", 1.0, 0.0, 1024.0).setSyncable(true));
		OverhauledDamage.BLEEDING_BUILD_UP_REDUCTION_DELAY_THRESHOLD = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.bleeding_build_up_reduction_delay_threshold"), new RangedAttribute("attribute.name.generic.bleeding_build_up_reduction_delay_threshold", 40.0, 0.0, 1024.0).setSyncable(true));

		OverhauledDamage.ADDITIONAL_FROST_DAMAGE = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.additional_frost_damage"), new RangedAttribute("attribute.name.generic.additional_frost_damage", 0.0, -1024.0, 1024.0).setSyncable(true));
		OverhauledDamage.INCREASED_FROST_DAMAGE = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.increased_frost_damage"), new RangedAttribute("attribute.name.generic.increased_frost_damage", 1.0, -1024.0, 1024.0).setSyncable(true));
		OverhauledDamage.BLOCKED_FROST_DAMAGE = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.blocked_frost_damage"), new RangedAttribute("attribute.name.generic.blocked_frost_damage", 0.0, 0.0, 1024.0).setSyncable(true));
		OverhauledDamage.FROST_RESISTANCE = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.frost_resistance"), new RangedAttribute("attribute.name.generic.frost_resistance", 0.0, -1024.0, 1024.0).setSyncable(true));
		OverhauledDamage.MAX_FREEZE_BUILD_UP = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.max_freeze_build_up"), new RangedAttribute("attribute.name.generic.max_freeze_build_up", 20.0, -1.0, 1024.0).setSyncable(true));
		OverhauledDamage.FREEZE_DURATION = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.freeze_duration"), new RangedAttribute("attribute.name.generic.freeze_duration", 200.0, 1.0, 1000000.0).setSyncable(true));
		OverhauledDamage.FREEZE_TICK_THRESHOLD = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.freeze_tick_threshold"), new RangedAttribute("attribute.name.generic.freeze_tick_threshold", 20.0, 0.0, 1024.0).setSyncable(true));
		OverhauledDamage.FREEZE_BUILD_UP_REDUCTION = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.freeze_build_up_reduction"), new RangedAttribute("attribute.name.generic.freeze_build_up_reduction", 1.0, 0.0, 1024.0).setSyncable(true));
		OverhauledDamage.FREEZE_BUILD_UP_REDUCTION_DELAY_THRESHOLD = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.freeze_build_up_reduction_delay_threshold"), new RangedAttribute("attribute.name.generic.freeze_build_up_reduction_delay_threshold", 40.0, 0.0, 1024.0).setSyncable(true));

		OverhauledDamage.ADDITIONAL_FIRE_DAMAGE = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.additional_fire_damage"), new RangedAttribute("attribute.name.generic.additional_fire_damage", 0.0, -1024.0, 1024.0).setSyncable(true));
		OverhauledDamage.INCREASED_FIRE_DAMAGE = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.increased_fire_damage"), new RangedAttribute("attribute.name.generic.increased_fire_damage", 1.0, -1024.0, 1024.0).setSyncable(true));
		OverhauledDamage.BLOCKED_FIRE_DAMAGE = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.blocked_fire_damage"), new RangedAttribute("attribute.name.generic.blocked_fire_damage", 0.0, 0.0, 1024.0).setSyncable(true));
		OverhauledDamage.FIRE_RESISTANCE = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.fire_resistance"), new RangedAttribute("attribute.name.generic.fire_resistance", 0.0, -1024.0, 1024.0).setSyncable(true));
		OverhauledDamage.MAX_BURN_BUILD_UP = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.max_burn_build_up"), new RangedAttribute("attribute.name.generic.max_burn_build_up", 20.0, -1.0, 1024.0).setSyncable(true));
		OverhauledDamage.BURN_DURATION = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.burn_duration"), new RangedAttribute("attribute.name.generic.burn_duration", 351.0, 1.0, 1000000.0).setSyncable(true));
		OverhauledDamage.BURN_TICK_THRESHOLD = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.burn_tick_threshold"), new RangedAttribute("attribute.name.generic.burn_tick_threshold", 20.0, 0.0, 1024.0).setSyncable(true));
		OverhauledDamage.BURN_BUILD_UP_REDUCTION = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.burn_build_up_reduction"), new RangedAttribute("attribute.name.generic.burn_build_up_reduction", 1.0, 0.0, 1024.0).setSyncable(true));
		OverhauledDamage.BURN_BUILD_UP_REDUCTION_DELAY_THRESHOLD = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.burn_build_up_reduction_delay_threshold"), new RangedAttribute("attribute.name.generic.burn_build_up_reduction_delay_threshold", 40.0, 0.0, 1024.0).setSyncable(true));

		OverhauledDamage.ADDITIONAL_LIGHTNING_DAMAGE = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.additional_lightning_damage"), new RangedAttribute("attribute.name.generic.additional_lightning_damage", 0.0, -1024.0, 1024.0).setSyncable(true));
		OverhauledDamage.INCREASED_LIGHTNING_DAMAGE = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.increased_lightning_damage"), new RangedAttribute("attribute.name.generic.increased_lightning_damage", 1.0, -1024.0, 1024.0).setSyncable(true));
		OverhauledDamage.BLOCKED_LIGHTNING_DAMAGE = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.blocked_lightning_damage"), new RangedAttribute("attribute.name.generic.blocked_lightning_damage", 0.0, 0.0, 1024.0).setSyncable(true));
		OverhauledDamage.LIGHTNING_RESISTANCE = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.lightning_resistance"), new RangedAttribute("attribute.name.generic.lightning_resistance", 0.0, -1024.0, 1024.0).setSyncable(true));
		OverhauledDamage.MAX_SHOCK_BUILD_UP = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.max_shock_build_up"), new RangedAttribute("attribute.name.generic.max_shock_build_up", 20.0, -1.0, 1024.0).setSyncable(true));
		OverhauledDamage.SHOCK_DURATION = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.shock_duration"), new RangedAttribute("attribute.name.generic.shock_duration", 1.0, 1.0, 1000000.0).setSyncable(true));
		OverhauledDamage.SHOCK_TICK_THRESHOLD = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.shock_tick_threshold"), new RangedAttribute("attribute.name.generic.shock_tick_threshold", 20.0, 0.0, 1024.0).setSyncable(true));
		OverhauledDamage.SHOCK_BUILD_UP_REDUCTION = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.shock_build_up_reduction"), new RangedAttribute("attribute.name.generic.shock_build_up_reduction", 1.0, 0.0, 1024.0).setSyncable(true));
		OverhauledDamage.SHOCK_BUILD_UP_REDUCTION_DELAY_THRESHOLD = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.shock_build_up_reduction_delay_threshold"), new RangedAttribute("attribute.name.generic.shock_build_up_reduction_delay_threshold", 40.0, 0.0, 1024.0).setSyncable(true));

		OverhauledDamage.ADDITIONAL_POISON_DAMAGE = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.additional_poison_damage"), new RangedAttribute("attribute.name.generic.additional_poison_damage", 0.0, -1024.0, 1024.0).setSyncable(true));
		OverhauledDamage.INCREASED_POISON_DAMAGE = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.increased_poison_damage"), new RangedAttribute("attribute.name.generic.increased_poison_damage", 1.0, -1024.0, 1024.0).setSyncable(true));
		OverhauledDamage.BLOCKED_POISON_DAMAGE = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.blocked_poison_damage"), new RangedAttribute("attribute.name.generic.blocked_poison_damage", 0.0, 0.0, 1024.0).setSyncable(true));
		OverhauledDamage.POISON_RESISTANCE = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.poison_resistance"), new RangedAttribute("attribute.name.generic.poison_resistance", 0.0, -1024.0, 1024.0).setSyncable(true));
		OverhauledDamage.MAX_POISON_BUILD_UP = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.max_poison_build_up"), new RangedAttribute("attribute.name.generic.max_poison_build_up", 20.0, -1.0, 1024.0).setSyncable(true));
		OverhauledDamage.POISON_DURATION = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.poison_duration"), new RangedAttribute("attribute.name.generic.poison_duration", 201.0, 1.0, 1000000.0).setSyncable(true));
		OverhauledDamage.POISON_TICK_THRESHOLD = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.poison_tick_threshold"), new RangedAttribute("attribute.name.generic.poison_tick_threshold", 20.0, 0.0, 1024.0).setSyncable(true));
		OverhauledDamage.POISON_BUILD_UP_REDUCTION = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.poison_build_up_reduction"), new RangedAttribute("attribute.name.generic.poison_build_up_reduction", 1.0, 0.0, 1024.0).setSyncable(true));
		OverhauledDamage.POISON_BUILD_UP_REDUCTION_DELAY_THRESHOLD = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.poison_build_up_reduction_delay_threshold"), new RangedAttribute("attribute.name.generic.poison_build_up_reduction_delay_threshold", 40.0, 0.0, 1024.0).setSyncable(true));

		OverhauledDamage.MAX_STAGGER_BUILD_UP = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.max_stagger_build_up"), new RangedAttribute("attribute.name.generic.max_stagger_build_up", 20.0, -1.0, 1024.0).setSyncable(true));
		OverhauledDamage.STAGGER_DURATION = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.stagger_duration"), new RangedAttribute("attribute.name.generic.stagger_duration", 200.0, 1.0, 1000000.0).setSyncable(true));
		OverhauledDamage.STAGGER_TICK_THRESHOLD = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.stagger_tick_threshold"), new RangedAttribute("attribute.name.generic.stagger_tick_threshold", 20.0, 0.0, 1024.0).setSyncable(true));
		OverhauledDamage.STAGGER_BUILD_UP_REDUCTION = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.stagger_build_up_reduction"), new RangedAttribute("attribute.name.generic.stagger_build_up_reduction", 1.0, 0.0, 1024.0).setSyncable(true));
		OverhauledDamage.STAGGER_BUILD_UP_REDUCTION_DELAY_THRESHOLD = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.stagger_build_up_reduction_delay_threshold"), new RangedAttribute("attribute.name.generic.stagger_build_up_reduction_delay_threshold", 40.0, 0.0, 1024.0).setSyncable(true));

		OverhauledDamage.DAMAGE_TAKEN_FROM_MANA_MULTIPLIER = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.damage_taken_from_mana_multiplier"), new RangedAttribute("attribute.name.generic.damage_taken_from_mana_multiplier", 0.0, 0.0, 1024.0).setSyncable(true));
		OverhauledDamage.DAMAGE_TAKEN_FROM_STAMINA_MULTIPLIER = Registry.registerForHolder(BuiltInRegistries.ATTRIBUTE, OverhauledDamage.identifier("generic.damage_taken_from_stamina_multiplier"), new RangedAttribute("attribute.name.generic.damage_taken_from_stamina_multiplier", 0.0, 0.0, 1024.0).setSyncable(true));
	}
}
